package com.yidao.threekmo.db_bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yidao.threekmo.db_bean.SearchHistroyBean;

import com.yidao.threekmo.db_bean.SearchHistroyBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistroyBeanDaoConfig;

    private final SearchHistroyBeanDao searchHistroyBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistroyBeanDaoConfig = daoConfigMap.get(SearchHistroyBeanDao.class).clone();
        searchHistroyBeanDaoConfig.initIdentityScope(type);

        searchHistroyBeanDao = new SearchHistroyBeanDao(searchHistroyBeanDaoConfig, this);

        registerDao(SearchHistroyBean.class, searchHistroyBeanDao);
    }
    
    public void clear() {
        searchHistroyBeanDaoConfig.clearIdentityScope();
    }

    public SearchHistroyBeanDao getSearchHistroyBeanDao() {
        return searchHistroyBeanDao;
    }

}
